#!/usr/bin/env python3
"""
SCOPE Teams Alert Message GIF Generator
Creates animated GIF showing SCOPE threat analysis appearing as Teams message
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from matplotlib.patches import Rectangle, FancyBboxPatch
import matplotlib.patches as mpatches
from datetime import datetime
import io
from PIL import Image, ImageDraw, ImageFont

class SCOPEAlertAnimation:
    def __init__(self):
        self.fig, self.ax = plt.subplots(figsize=(12, 8))
        self.fig.patch.set_facecolor('#f5f5f5')  # Teams background
        
        # Animation state
        self.frame_count = 0
        self.message_opacity = 0
        self.typewriter_chars = 0
        self.pulse_phase = 0
        
        # Message content
        self.full_message = """🔵 SCOPE THREAT ANALYSIS PING 🔵

🕐 Generated: 2026-03-22 13:39:22
📡 Current Status: LIVE FAKE DATA MODE
🎯 Analysis: Real-time threat assessment ping

📊 CURRENT THREAT ASSESSMENT:
• Threat Level: MODERATE (43.8/100)
• People Detected: 2
• Sound Level: 59.4 dB
• Air Quality: AQI 277.1
• 1-Hour Average: 0.0/100
• Peak Threat: 0.0/100

⚡ URGENCY: 📊 INCREASED AWARENESS

🧠 Analysis: Moderate threat levels - normal monitoring with increased awareness

🎯 IMMEDIATE ACTIONS:
• Continue routine monitoring with increased attention
• Verify sensor calibration
• Prepare response protocols
• Maintain standard security posture

Environmental Factors:
• 💨 Poor air quality: AQI 277.1

📋 Recent Activity:
  1. 4.429094 - Threat: 47.0/100 - ELEVATED threat detected with 3 people
  2. 9.462700 - Threat: 16.5/100 - LOW threat detected with 1 people
  3. 6.153664 - Threat: 31.5/100 - MODERATE threat detected with 1 people

---
🤖 This analysis was generated by SCOPE system based on current threat assessment.
📱 For detailed reports and live monitoring, check the SCOPE dashboard."""
        
        self.setup_teams_interface()
        
    def setup_teams_interface(self):
        """Setup Teams-like interface"""
        self.ax.set_xlim(0, 12)
        self.ax.set_ylim(0, 8)
        self.ax.axis('off')
        
        # Teams header
        self.create_teams_header()
        
        # Message container
        self.create_message_container()
        
        # SCOPE avatar
        self.create_scope_avatar()
        
        # Message elements (initially hidden)
        self.message_elements = []
        
    def create_teams_header(self):
        """Create Teams header bar"""
        # Header background
        header = Rectangle((0, 7.2), 12, 0.8, facecolor='#464775', edgecolor='none')
        self.ax.add_patch(header)
        
        # Teams logo area
        logo_area = Rectangle((0.2, 7.3), 0.6, 0.6, facecolor='#7b83eb', edgecolor='none')
        self.ax.add_patch(logo_area)
        
        # Channel name
        self.ax.text(1.0, 7.6, '# SCOPE-Alerts', fontsize=12, color='white', 
                   fontweight='bold', va='center')
        
        # Search bar
        search_bar = Rectangle((9, 7.4), 2.8, 0.4, facecolor='#3b3b3b', edgecolor='#666666')
        self.ax.add_patch(search_bar)
        self.ax.text(9.2, 7.6, '🔍 Search', fontsize=10, color='#999999', va='center')
        
        # User area
        user_circle = plt.Circle((11.5, 7.6), 0.25, facecolor='#7b83eb', edgecolor='white')
        self.ax.add_patch(user_circle)
        
    def create_message_container(self):
        """Create message container with Teams styling"""
        # Message bubble
        self.message_box = FancyBboxPatch(
            (1.5, 1.5), 8.5, 5.5,
            boxstyle="round,pad=0.1",
            facecolor='white',
            edgecolor='#e1e1e1',
            linewidth=1
        )
        self.ax.add_patch(self.message_box)
        
        # Timestamp area (initially hidden)
        self.timestamp_text = self.ax.text(1.7, 6.8, '', fontsize=9, 
                                         color='#605e5c', va='top')
        
    def create_scope_avatar(self):
        """Create SCOPE system avatar"""
        # Avatar circle
        avatar_circle = plt.Circle((1.0, 3.5), 0.3, facecolor='#ff4444', 
                                edgecolor='white', linewidth=2)
        self.ax.add_patch(avatar_circle)
        
        # SCOPE text
        self.ax.text(1.0, 3.5, 'S', fontsize=14, color='white', 
                   fontweight='bold', ha='center', va='center')
        
        # Online indicator
        online_circle = plt.Circle((1.25, 3.25), 0.08, facecolor='#00ff00', 
                                edgecolor='white', linewidth=1)
        self.ax.add_patch(online_circle)
        
        # System name
        self.scope_name = self.ax.text(1.0, 3.0, 'SCOPE System', 
                                     fontsize=8, color='#605e5c', 
                                     ha='center', va='top')
        
    def create_teams_sidebar(self):
        """Create Teams sidebar elements"""
        # Sidebar background
        sidebar = Rectangle((0, 0), 1.2, 7.2, facecolor='#2b2d30', edgecolor='none')
        self.ax.add_patch(sidebar)
        
        # Navigation items
        nav_items = [
            ('🏠', 6.5, 'Activity'),
            ('💬', 6.0, 'Chat'),
            ('👥', 5.5, 'Teams'),
            ('📅', 5.0, 'Calendar'),
            ('📞', 4.5, 'Calls')
        ]
        
        for icon, y, label in nav_items:
            self.ax.text(0.6, y, icon, fontsize=16, ha='center', va='center')
            
    def format_message_text(self, text, max_chars=None):
        """Format message with proper line breaks and styling"""
        if max_chars:
            text = text[:max_chars]
        
        # Replace emojis and format
        formatted_lines = []
        for line in text.split('\n'):
            if line.strip():
                # Handle different line types
                if line.startswith('🔵') or line.startswith('🕐') or line.startswith('📡'):
                    formatted_lines.append((line, 'header', '#0078d4'))
                elif line.startswith('📊') or line.startswith('⚡') or line.startswith('🧠'):
                    formatted_lines.append((line, 'subheader', '#444444'))
                elif line.startswith('🎯'):
                    formatted_lines.append((line, 'subheader', '#444444'))
                elif line.startswith('•'):
                    formatted_lines.append((line, 'bullet', '#605e5c'))
                elif line.startswith('Environmental'):
                    formatted_lines.append((line, 'section', '#0078d4'))
                elif line.startswith('📋'):
                    formatted_lines.append((line, 'section', '#0078d4'))
                elif line.startswith('  '):
                    formatted_lines.append((line, 'indented', '#605e5c'))
                elif line.startswith('---'):
                    formatted_lines.append((line, 'separator', '#e1e1e1'))
                elif line.startswith('🤖') or line.startswith('📱'):
                    formatted_lines.append((line, 'footer', '#999999'))
                else:
                    formatted_lines.append((line, 'normal', '#323130'))
            else:
                formatted_lines.append(('', 'normal', '#323130'))
        
        return formatted_lines
        
    def update(self, frame):
        """Update animation frame"""
        self.frame_count = frame
        self.pulse_phase = frame * 0.1
        
        # Clear previous message elements
        for element in self.message_elements:
            element.remove()
        self.message_elements = []
        
        # Animation phases
        if frame < 20:
            # Phase 1: Avatar appears with pulse
            self.animate_avatar_appearance()
            
        elif frame < 30:
            # Phase 2: "Typing..." indicator
            self.animate_typing_indicator()
            
        elif frame < 150:
            # Phase 3: Message appears with typewriter effect
            self.animate_message_typewriter()
            
        else:
            # Phase 4: Final state with subtle pulse
            self.animate_final_state()
        
        return self.message_elements
    
    def animate_avatar_appearance(self):
        """Animate avatar appearing"""
        progress = self.frame_count / 20
        
        # Avatar pulse
        scale = 1.0 + 0.1 * np.sin(self.pulse_phase)
        alpha = min(1.0, max(0.0, progress))  # Clamp alpha to 0-1 range
        avatar_circle = plt.Circle((1.0, 3.5), 0.3 * scale, 
                                facecolor='#ff4444', edgecolor='white', 
                                linewidth=2, alpha=alpha)
        self.ax.add_patch(avatar_circle)
        self.message_elements.append(avatar_circle)
        
        # SCOPE text
        text_alpha = min(1.0, max(0.0, progress))  # Clamp alpha to 0-1 range
        scope_text = self.ax.text(1.0, 3.5, 'S', fontsize=14, color='white', 
                                fontweight='bold', ha='center', va='center', 
                                alpha=text_alpha)
        self.message_elements.append(scope_text)
        
        # Online indicator (pulsing)
        online_size = 0.08 + 0.02 * np.sin(self.pulse_phase * 2)
        online_alpha = min(1.0, max(0.0, progress))  # Clamp alpha to 0-1 range
        online_circle = plt.Circle((1.25, 3.25), online_size, facecolor='#00ff00', 
                                edgecolor='white', linewidth=1, alpha=online_alpha)
        self.ax.add_patch(online_circle)
        self.message_elements.append(online_circle)
        
        # System name
        name_alpha = min(1.0, max(0.0, progress))  # Clamp alpha to 0-1 range
        scope_name = self.ax.text(1.0, 3.0, 'SCOPE System', 
                                 fontsize=8, color='#605e5c', 
                                 ha='center', va='top', alpha=name_alpha)
        self.message_elements.append(scope_name)
        
    def animate_typing_indicator(self):
        """Show typing indicator"""
        # Avatar (fully visible)
        self.animate_avatar_appearance()
        
        # Typing dots
        typing_text = "SCOPE System is typing"
        dots = "." * ((self.frame_count - 20) % 4)
        full_typing = typing_text + dots
        
        typing_message = self.ax.text(2.0, 3.5, full_typing, fontsize=11, 
                                   color='#605e5c', style='italic')
        self.message_elements.append(typing_message)
        
    def animate_message_typewriter(self):
        """Animate message appearing with typewriter effect"""
        # Avatar (fully visible)
        self.animate_avatar_appearance()
        
        # Calculate typewriter progress
        typewriter_progress = (self.frame_count - 30) / 120
        chars_to_show = int(len(self.full_message) * typewriter_progress)
        
        # Show timestamp
        timestamp = self.ax.text(1.7, 6.8, '2026-03-22 13:39:22', 
                                fontsize=9, color='#605e5c', va='top')
        self.message_elements.append(timestamp)
        
        # Format and display message
        message_text = self.full_message[:chars_to_show]
        formatted_lines = self.format_message_text(message_text)
        
        y_pos = 6.5
        for line_text, line_type, color in formatted_lines:
            if line_text.strip():
                if line_type == 'header':
                    text_element = self.ax.text(2.0, y_pos, line_text, fontsize=10, 
                                             color=color, fontweight='bold', va='top')
                elif line_type == 'subheader':
                    text_element = self.ax.text(2.0, y_pos, line_text, fontsize=9, 
                                             color=color, fontweight='bold', va='top')
                elif line_type == 'bullet':
                    text_element = self.ax.text(2.0, y_pos, line_text, fontsize=9, 
                                             color=color, va='top')
                elif line_type == 'section':
                    text_element = self.ax.text(2.0, y_pos, line_text, fontsize=9, 
                                             color=color, fontweight='bold', va='top')
                elif line_type == 'indented':
                    text_element = self.ax.text(2.2, y_pos, line_text, fontsize=8, 
                                             color=color, va='top')
                elif line_type == 'separator':
                    text_element = self.ax.text(2.0, y_pos, line_text, fontsize=8, 
                                             color=color, va='top')
                elif line_type == 'footer':
                    text_element = self.ax.text(2.0, y_pos, line_text, fontsize=8, 
                                             color=color, va='top', style='italic')
                else:
                    text_element = self.ax.text(2.0, y_pos, line_text, fontsize=9, 
                                             color=color, va='top')
                
                self.message_elements.append(text_element)
                y_pos -= 0.15
    
    def animate_final_state(self):
        """Show final state with subtle effects"""
        # Show complete message
        self.animate_message_typewriter()
        
        # Add subtle glow effect to message box
        glow_alpha = 0.05 + 0.02 * np.sin(self.pulse_phase)
        glow_box = FancyBboxPatch(
            (1.48, 1.48), 8.54, 5.54,
            boxstyle="round,pad=0.12",
            facecolor='#0078d4',
            alpha=glow_alpha,
            edgecolor='none'
        )
        self.ax.add_patch(glow_box)
        self.message_elements.append(glow_box)
    
    def create_gif(self, filename='scope_teams_alert.gif', frames=180):
        """Create the animated GIF"""
        print(f"🔵 Creating SCOPE Teams Alert GIF: {filename}")
        
        anim = animation.FuncAnimation(
            self.fig, self.update, frames=frames,
            interval=50, blit=False, repeat=True
        )
        
        # Save as GIF
        print("📽️ Rendering frames...")
        anim.save(filename, writer='pillow', fps=20, dpi=100)
        print(f"✅ Saved: {filename}")
        
        # Also save individual frames for debugging
        if frames <= 10:
            for i in range(frames):
                self.update(i)
                plt.savefig(f'scope_teams_frame_{i:02d}.png', 
                           dpi=100, bbox_inches='tight', 
                           facecolor=self.fig.get_facecolor())
        
        plt.close()

def main():
    """Main function"""
    print("=" * 60)
    print("🔵 SCOPE TEAMS ALERT MESSAGE GENERATOR")
    print("=" * 60)
    print("📱 Creating animated Teams message showing:")
    print("   • SCOPE threat analysis ping")
    print("   • Real-time threat assessment")
    print("   • Teams-like interface")
    print("   • Typewriter animation effect")
    print("   • Professional alert styling")
    print()
    
    # Create animation
    scope_alert = SCOPEAlertAnimation()
    scope_alert.create_gif('scope_teams_alert.gif', frames=180)
    
    print()
    print("🎯 Animation phases:")
    print("   1. Avatar appears (frames 0-20)")
    print("   2. Typing indicator (frames 20-30)")
    print("   3. Message typewriter (frames 30-150)")
    print("   4. Final state with glow (frames 150-180)")
    print()
    print("✅ SCOPE Teams alert animation complete!")

if __name__ == "__main__":
    main()
